_target_: src.evaluators.batch_in_context_evaluator.BatchInContextEvaluator
config:
  name: "batch_same_subject_in_context"
  system_prompt: "You are an expert answering multiple choice questions. Analyze the question carefully and select the ONE correct option. Output ONLY the capital letter of your choice with NO additional text or explanation."
  num_shots: 5
  output_dir: "${hydra:runtime.output_dir}/results/"
  extract_hidden_states: false 
  batch_size: 16384