# 设置变量
model="deepseek-qwen3-8b"
dataset="mmlu"
bash scripts/download_model_dataset.sh ${model} ${dataset}
method="emb_gen"
pool_method="mean"

subjects=(
    "anatomy"
    "astronomy"
    "business_ethics"
    "clinical_knowledge"
    "college_biology"
    "college_chemistry"
    "college_computer_science"
    "college_mathematics"
    "college_medicine"
    "college_physics"
    "computer_security"
    "conceptual_physics"
    "econometrics"
    "electrical_engineering"
    "elementary_mathematics"
    "formal_logic"
    "global_facts"
    "high_school_biology"
    "high_school_chemistry"  
    "high_school_computer_science"
    "high_school_european_history"
    "high_school_geography"
    "high_school_government_and_politics"
    "high_school_macroeconomics"
    "high_school_mathematics"
    "high_school_microeconomics"
    "high_school_physics"
    "high_school_psychology"
    "high_school_statistics"
    "high_school_us_history"
    "high_school_world_history"
    "human_aging"
    "human_sexuality"
    "international_law"
    "judicial_methodology"
    "logical_fallacies"
    "machine_learning"
    "management"
    "marketing"
    "medical_genetics"
    "miscellaneous"
    "moral_disputes"
    "moral_scenarios"
    "nutrition"
    "philosophy"
    "prehistory"
    "professional_accounting"
    "professional_law"
    "professional_medicine"
    "professional_psychology"
    "public_relations"
    "security_studies"
    "sociology"
    "us_foreign_policy"
    "virology"
    "world_religions"
)
mkdir -p log

for subject in "${subjects[@]}"; do
    experiment_name="${model}_${dataset}-{$subject}_${method}_{$pool_method}"
    python3 main.py evaluation=emb_gen model=deepseek dataset.config.subjects="[$subject]" evaluation.config.pool_method="$pool_method" | tee "log/${experiment_name}.txt"

    # 可选上传结果
    if [ -f "scripts/s3upload.sh" ]; then
        bash scripts/s3upload.sh "log/${experiment_name}"
    else
        echo "No s3upload.sh script found. Result will be saved locally."
    fi
done
